# Sample workflow for building and deploying an Eleventy site to GitHub Pages
name: Deploy Eleventy with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main","preprod"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build with Eleventy
        run: |
          npm install
          npm run build
      - name: Index site for pagefind
        run: npm run postbuild
      - name: fr fallback homepage
        run: "cp _site/fr/index.html _site/index.html"

  # Deployment job
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp-mediationlogement.alwaysdata.net
          username: mediationlogement_github
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
